name: Lint PHP

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint-php:
    name: Lint PHP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer:v2

      - name: Validate Composer files
        run: composer validate --no-check-publish

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --no-plugins --no-scripts

      - name: Configure PHPCS standards
        run: ./vendor/bin/phpcs --config-set installed_paths ../../phpcsstandards/phpcsextra,../../phpcsstandards/phpcsutils,../../wp-coding-standards/wpcs

      - name: Install scoped dependencies
        run: composer run wpify:install

      - name: Check syntax
        run: find enable-list-icons.php inc scripts -name '*.php' -print0 | xargs -0 -n1 php -l

      - name: Lint PHP
        run: ./vendor/bin/phpcs enable-list-icons.php inc -v --standard='./phpcs.xml'

      - name: Static analysis
        run: composer run phpstan
