name: Lint and Build

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    lint-build:
        name: Lint and Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Set up Node
              uses: actions/setup-node@v6
              with:
                  node-version: 20
                  cache: npm

            - name: Install dependencies
              run: npm install

            - name: Lint JavaScript
              run: npm run lint:js

            - name: Lint CSS
              run: npm run lint:css

            - name: Build
              run: npm run build

    php:
        name: PHP Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  tools: composer

            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist

            - name: PHPCodeSniffer
              run: composer phpsniff

            - name: Static Analysis
              run: composer phpstan

            - name: PHPUnit
              run: composer test
